LIST_OF_SEPARATORS = [' ', '.', "/", "\\", "_", "@"]
LIST_OF_JOINERS =['&', '+', '-', "'", "`"]

TEST_EXAMPLES = ['J H Selection Works ',
                 'I.B. Construction   ',
                 'KS of Construction  ',
                 'CM Selection Works  ',
                 'C & A reworks       ',
                 "Q's Construction se ",
                 'TLC renovation      ',
                 'G. B. Building      ',
                 'V & M Industrial    ',
                 'Top K Production    ',
                 'J. Data Reworks     ',
                 'D.O.M.              ',
                 'Eighty-Eight Constr ',
                 "O'Boyle Production  ",
                 "Carrilo's Rebuildng ",
                 'J-Mac renovation & b',
                 'A.L.L. Construction ',
                 'Rmc/Gc builders     ',
                 'A.w. renovation     ',
                 '2Cg, Inc.           ',
                 '5 N 1 builders      ',
                 'J&L general contract',
                 'Jc Ac builders      ',
                 '34-Ten production   ',
                 'D+K builders        ',
                 'von Nemetz Construct',
                 'J p Construction & M',
                 'GB&D renovators     ',
                 'khu@7shi            ',
                 'Allen+Pepa Construct',
                 'G C M Construction  ',
                 'T-N-D Builders      ']